pipline:
  name: "house-price-data-pipeline"
  version: "1.0.0"
  description: "Pipeline for processing house price data"

paths:
  raw_data_dir: "data/raw/"
  processed_data_dir: "data/processed/"
  output_filename: "house_price_predictions.parquet"

execution:
  skip_existing: true
  skip_ingest_if_exists: true
  force_download: false
  force_ingest: false

logging:
  name: IngestaoLogger
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
  log_to_file: true
  log_dir: logs
  log_file: pipeline.log