preprocessing:
  output_dir: "data/features"
  output_filename: "kingcounty_features.parquet"
  compression: "snappy"

# -----------------------------
# IMPUTAÇÃO
# -----------------------------
# O dataset King County NÃO tem "total_bedrooms" nem "ocean_proximity".
# Mas tem valores 0 em "sqft_basement" e "yr_renovated".
# Vamos imputar "yr_renovated" = 0 como "não renovado".

imputation:
  - column: "yr_renovated"
    strategy: "constant"
    fill_value: 0
    group_by: "zipcode"

# -----------------------------
# BINARY FLAGS
# -----------------------------
# Criar flag para casas muito antigas
binary_flags:
  - column: "yr_built"
    value: 1950
    new_column: "built_before_1950"

# -----------------------------
# RATIO FEATURES
# -----------------------------
ratio_features:
  - name: "bath_per_bed"
    numerator: "bathrooms"
    denominator: "bedrooms"

  - name: "sqft_living_per_room"
    numerator: "sqft_living"
    denominator: "bedrooms"

  - name: "lot_per_sqft"
    numerator: "sqft_lot"
    denominator: "sqft_living"

# -----------------------------
# LOG TRANSFORM
# -----------------------------
log_transformer:
  columns:
    - "sqft_living"
    - "sqft_lot"
    - "sqft_above"
    - "sqft_basement"
    - "price"

# -----------------------------
# GEO DISTANCE
# -----------------------------
# Agora usando cidades próximas de Seattle
geo_distance:
  lat_col: "lat"
  lon_col: "long"
  nearest_city_column: "nearest_city_distance"
  cities:
    - name: "seattle"
      lat: 47.6062
      lon: -122.3321
    - name: "bellevue"
      lat: 47.6101
      lon: -122.2015
    - name: "redmond"
      lat: 47.673988
      lon: -122.121513
    - name: "tacoma"
      lat: 47.2529
      lon: -122.4443
    - name: "everett"
      lat: 47.978984
      lon: -122.202079

# Aplicando funçao polinomial pela relaçao nao linear do tamanho x preco
polynomial_features:
  - name: "sqft_living_squared"
    columns: ["sqft_living"]
  # Analisando a relacao quantidade de banheiro x quantidade de quartos
  - name: "bath_x_bed"
    columns: ["bathrooms", "bedrooms"]

# Usando "zipcode" com one-hot para categorizar os imóveis pela regiao.
categorical_encoding:
  column: "zipcode"
  one_hot_prefix: "zip"
  drop_first: false

# -----------------------------
# FEATURE SELECTION
# -----------------------------
feature_selection:
  target: "price"
  features_to_keep:
    - "sqft_living"
    - "sqft_lot"
    - "sqft_above"
    - "sqft_basement"
    - "bathrooms"
    - "bedrooms"
    - "floors"
    - "waterfront"
    - "view"
    - "condition"
    - "grade"
    - "yr_built"
    - "yr_renovated"
    - "lat"
    - "long"
    - "built_before_1950"
    - "bath_per_bed"
    - "sqft_living_per_room"
    - "lot_per_sqft"
    - "nearest_city_distance"
    - "sqft_living_squared"
    - "bath_x_bed"