quality:
  suite_name: "house-price-data-quality-suite"
  fail_pipeline_on_failure: False
  output_dir: "data/quality/"
table_expectations:
  - type: "expect_table_row_count_to_be_between"
    kwargs:
      min_value: 20000
      max_value: 21000  
  - type: "expect_table_columns_to_match_set"
    kwargs:
      column_set:
        - "median_house_value"
        - "median_income"
        - "housing_median_age"
        - "total_rooms"
        - "total_bedrooms"
        - "population"
        - "households"
        - "longitude"
        - "latitude"
        - "ocean_proximity"
      exact_match: true
column_expectations:
  median_house_value:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 0
        max_value: 600000
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99
    - type: "expect_column_mean_to_be_between"
      kwargs:
        min_value: 150000
        max_value: 270000
  median_income:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 0
        max_value: 150000
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99
  housing_median_age:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1
        max_value: 60
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99
  total_rooms:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1
        max_value: null # no upper limit
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99
  total_bedrooms:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1
        max_value: null # no upper limit
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.98
  population:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1
        max_value: null # no upper limit
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99
  households:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1
        max_value: null # no upper limit
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99
  longitude:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: -180
        max_value: 180
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99
  latitude:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: -90
        max_value: 90
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99
  ocean_proximity:
    - type: "expect_column_values_to_be_in_set"
      kwargs:
        value_set:
          - "NEAR OCEAN"
          - "INLAND"
          - "NEAR BAY"
          - "ISLAND"
          - "BACK INLAND"
          - "<1H OCEAN"
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.99