quality:
  suite_name: "kingcounty-data-quality-suite"
  fail_pipeline_on_failure: False
  output_dir: "data/quality/"

table_expectations:
  - type: "expect_table_row_count_to_be_between"
    kwargs:
      min_value: 21000
      max_value: 22000

  - type: "expect_table_columns_to_match_set"
    kwargs:
      column_set:
        - "id"
        - "date"
        - "price"
        - "bedrooms"
        - "bathrooms"
        - "sqft_living"
        - "sqft_lot"
        - "floors"
        - "waterfront"
        - "view"
        - "condition"
        - "grade"
        - "sqft_above"
        - "sqft_basement"
        - "yr_built"
        - "yr_renovated"
        - "zipcode"
        - "lat"
        - "long"
        - "sqft_living15"
        - "sqft_lot15"
      exact_match: true

column_expectations:

  price:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 50000
        max_value: 8000000
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.999

  bedrooms:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 0
        max_value: 10
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.999

  bathrooms:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 0
        max_value: 8
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.999

  sqft_living:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 200
        max_value: 15000
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.999

  sqft_lot:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 400
        max_value: 1000000
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.999

  floors:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1
        max_value: 4

  waterfront:
    - type: "expect_column_values_to_be_in_set"
      kwargs:
        value_set: [0, 1]

  view:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 0
        max_value: 4

  condition:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1
        max_value: 5

  grade:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1
        max_value: 13

  yr_built:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 1900
        max_value: 2020

  yr_renovated:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 0
        max_value: 2020

  zipcode:
    - type: "expect_column_values_to_not_be_null"
      kwargs:
        mostly: 0.999

  lat:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: 47.0
        max_value: 48.0

  long:
    - type: "expect_column_values_to_be_between"
      kwargs:
        min_value: -123.0
        max_value: -121.0
